### PR TITLE
fix: fusiform_similarity test in traverser for server 1.3.0

### PR DESCRIPTION
**Pull request by liuxiaocs7**
faild jobs: https://github.com/apache/incubator-hugegraph-ai/actions/runs/8673001982/job/23783894307

doc: https://hugegraph.apache.org/cn/docs/clients/restful-api/traverser/#3221-fusiform-similarity

image

pass in 1.2 and fail in 1.3?

Related PR: https://github.com/apache/incubator-hugegraph/pull/2458

### CODE REVIEW

**Comment by liuxiaocs7** [comment]
Note: here requires Python 3.9+: https://github.com/apache/incubator-hugegraph-ai/blob/4f48116100f3ce7c9b9074cbe9c2f9a5ad8432bb/hugegraph-python-client/setup.py#L44
In doc requires Python 3.8+: https://hugegraph.apache.org/docs/quickstart/hugegraph-ai/

 Seems like it needs to be unified?

**Comment by simon824** [comment]
refer to https://github.com/apache/incubator-hugegraph/pull/2458/files

**Review by simon824 — APPROVED** [review]
LGTM

**Review by imbajin — APPROVED** [review]
Already update the title & comment in https://github.com/apache/incubator-hugegraph/pull/2458#discussion_r1565319553

**Pull request merged**
